title: BlastCAD Docs
description: A documentation site for BlastCAD, built to provide clear guides, tutorials, and reference materials.
theme: just-the-docs

url: https://docs.blastcad.com

aux_links:
  BlastCAD: https://blastcad.com
